Tipo de Registro V (eventos)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

La respuesta contiene un registro de tipo "V" por cada evento detectado.

==================== ======= ==================================================
Campo                Tipo    Descripción
==================== ======= ==================================================
TipoReg              S(1)    Tipo de Registro - "V"
EvtCode              N(6)    Código de evento
EvtMessage           S(512)  Descripción del evento
==================== ======= ==================================================

