Nomenclatura
------------

Para describir el formato de los registros se utiliza la siguiente nomenclatura:

============ =================================== ======= ==================
Tipo de dato Descripción                         Ejemplo Ejemplo formateado
============ =================================== ======= ==================
S(6)         Campo alfanumérico de 6 caracteres  AB123   "AB123 "
N(6)         Campo numérico entero de 6 dígitos  1234    "001234"
N(12,2)      Campo numérico de 12 dígitos        1234.56 "000000123456"
             (10 enteros y 2 decimales)
============ =================================== ======= ==================
