Errores comunes a todos los servicios WSFEX
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

====== ================================================================================
Código Descripción
====== ================================================================================
500    Error interno de aplicación
501    Error interno de base de datos
502    Error interno - Autorizador - Transacción Activa
====== ================================================================================
