Errores comunes a todos los servicios WSFE
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

====== ================================================================================
Código Descripción
====== ================================================================================
600    Usuario no autorizado a realizar esta operación
601    CUIT solicitante no se encuentra entre sus representados
====== ================================================================================
