Errores comunes a todos los servicios WSFE
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

====== ================================================================================
Código Descripción
====== ================================================================================
500    Error interno de aplicación
501    Error interno de base de datos
502    Error interno - Autorizador - Transacción Activa
600    No se corresponden token y firma. Usuario no autorizado a realizar esta operación
601    CUIT solicitante no se encuentra entre sus representados
602    No existen datos en los registros de la AFIP
====== ================================================================================
