Errores comunes a todos los servicios WSFE
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

====== ================================================================================
Código Descripción
====== ================================================================================
500    Error interno de aplicación
501    Error interno de base de datos
502    Error interno - Autorizador - Transacción Activa
600    No se corresponden token y firma. Usuario no autorizado a realizar esta operación
601    CUIT solicitante no se encuentra entre sus representados
602    No existen datos en los registros de la AFIP
900000 Error genérico
900001 Servicio no válido
900002 CUIT no informado
900003 No se encontró el certificado X.509
900004 No se encontró la clave privada
900005 No se pudo obtener un ticket de acceso
900006 Directorio no válido
900007 Argumento inválido o no informado
====== ================================================================================
